personal_information:
  name: "Ubba Huang"
  have_alias: true
  alias: "Ubbie"
  gender: "male"
  ethnicity:
    - "asian"

about_the_situation:
  which_situation: "dv"
  live_in_us: true
  state: "ca"
