version: '3.8'  

services:  
  db:  
    image: postgres:15-alpine  
    restart: always  
    environment:  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: myapp_development  
    ports:  
      - "5432:5432"  
    volumes:  
      - db_data:/var/lib/postgresql/data  

volumes:  
  db_data: 
